### ISSUE TITLE
Library has no tags/releases

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-twincat-physics#7]
@klauer is it ok if I make a tag for this library tomorrow? Probably an 0.1.0 or a 1.0.0

**Comment by klauer** [comment]
Yes - of course. Sorry for leaving it in the state it is!

**Comment by ZLLentz** [comment]
OK great, just making sure the no-tag wasn't an intentional choice
tag v0.1.0 is up and I'm going to upload the release blob
